default:
	@just --list

ray_lib_path := "/nix/store/lp7anw24jqsgyha19byxmb45833wxg15-raylib-5.5"
ray_gui_path := "/nix/store/jm9g8vxqxck5r85hz364i6zn2pf63vff-raygui"

alias b := build
alias c := commit
alias r := run

build:
	gcc main.c \
		-I {{ray_lib_path}}/include \
		-L {{ray_lib_path}}/lib \
		-lraylib -lm -lpthread -ldl -lrt \
		-o ptilo 

build-default:
	gcc main.c \
		-DMAIN_BG_COLOR=0x000033 \
		-DMAIN_TEXT_SIZE=20 \
		-DMAIN_TEXT_COLOR=0xCC66FFFF \
		-DMAIN_BORDER_COLOR=0x996633FF \
		-DINPUT_BG_COLOR=0x1A1A1AFF \
		-DINPUT_TEXT_SIZE=20 \
		-DINPUT_TEXT_COLOR=0xFFFFFFFF \
		-DINPUT_BORDER_COLOR=0x996633FF \
		-DINPUT_BASE_COLOR=0x1A1A1AFF \
		-DINPUT_BORDER_COLOR_FOCUSED=0x6B83FFFF \
		-DINPUT_BASE_COLOR_FOCUSED=0x2A2A2AFF \
		-DINPUT_TEXT_COLOR_FOCUSED=0xFFFFFFFF \
		-DINPUT_BORDER_WIDTH=2 \
		-DINPUT_TEXT_PADDING=5 \
		-DPSTYLES_TEXT_COLOR=RED \
		-DPSTYLES_TIMER_COLOR=ORANGE \
		-DBG_COLOR=BLACK \
		-I {{ray_lib_path}}/include \
		-L {{ray_lib_path}}/lib \
		-lraylib -lm -lpthread -ldl -lrt \
		-o main.out

build-dark:
	gcc main.c \
		-DMAIN_BG_COLOR=0x1A1A2EFF \
		-DMAIN_TEXT_SIZE=20 \
		-DMAIN_TEXT_COLOR=0xE0E0E0FF \
		-DMAIN_BORDER_COLOR=0x4A4A6AFF \
		-DINPUT_BG_COLOR=0x2D2D44FF \
		-DINPUT_TEXT_SIZE=20 \
		-DINPUT_TEXT_COLOR=0xE0E0E0FF \
		-DINPUT_BORDER_COLOR=0x4A4A6AFF \
		-DINPUT_BASE_COLOR=0x2D2D44FF \
		-DINPUT_BORDER_COLOR_FOCUSED=0x7B7BAAFF \
		-DINPUT_BASE_COLOR_FOCUSED=0x3D3D5AFF \
		-DINPUT_TEXT_COLOR_FOCUSED=0xFFFFFFFF \
		-DINPUT_BORDER_WIDTH=2 \
		-DINPUT_TEXT_PADDING=5 \
		-DPSTYLES_TEXT_COLOR=WHITE \
		-DPSTYLES_TIMER_COLOR=WHITE \
		-DBG_COLOR=BLACK \
		-I {{ray_lib_path}}/include \
		-L {{ray_lib_path}}/lib \
		-lraylib -lm -lpthread -ldl -lrt \
		-o main.out

build-light:
	gcc main.c \
		-DMAIN_BG_COLOR=0xF5F5F5FF \
		-DMAIN_TEXT_SIZE=20 \
		-DMAIN_TEXT_COLOR=0x2C3E50FF \
		-DMAIN_BORDER_COLOR=0xBDC3C7FF \
		-DINPUT_BG_COLOR=0xFFFFFFFF \
		-DINPUT_TEXT_SIZE=20 \
		-DINPUT_TEXT_COLOR=0x2C3E50FF \
		-DINPUT_BORDER_COLOR=0xBDC3C7FF \
		-DINPUT_BASE_COLOR=0xFFFFFFFF \
		-DINPUT_BORDER_COLOR_FOCUSED=0x3498DBFF \
		-DINPUT_BASE_COLOR_FOCUSED=0xECF0F1FF \
		-DINPUT_TEXT_COLOR_FOCUSED=0x2C3E50FF \
		-DINPUT_BORDER_WIDTH=2 \
		-DINPUT_TEXT_PADDING=5 \
		-DPSTYLES_TEXT_COLOR=BLACK \
		-DPSTYLES_TIMER_COLOR=GREEN \
		-DBG_COLOR=WHITE \
		-I {{ray_lib_path}}/include \
		-L {{ray_lib_path}}/lib \
		-lraylib -lm -lpthread -ldl -lrt \
		-o main.out

build-ocean:
	gcc main.c \
		-DMAIN_BG_COLOR=0x0A1929FF \
		-DMAIN_TEXT_SIZE=20 \
		-DMAIN_TEXT_COLOR=0x64FFDAFF \
		-DMAIN_BORDER_COLOR=0x0077B6FF \
		-DINPUT_BG_COLOR=0x112D4EFF \
		-DINPUT_TEXT_SIZE=20 \
		-DINPUT_TEXT_COLOR=0x64FFDAFF \
		-DINPUT_BORDER_COLOR=0x0077B6FF \
		-DINPUT_BASE_COLOR=0x112D4EFF \
		-DINPUT_BORDER_COLOR_FOCUSED=0x00B4D8FF \
		-DINPUT_BASE_COLOR_FOCUSED=0x1B4965FF \
		-DINPUT_TEXT_COLOR_FOCUSED=0x64FFDAFF \
		-DINPUT_BORDER_WIDTH=2 \
		-DINPUT_TEXT_PADDING=5 \
		-DPSTYLES_TEXT_COLOR=GRAY \
		-DPSTYLES_TIMER_COLOR=ORANGE \
		-DBG_COLOR=DARKBLUE \
		-I {{ray_lib_path}}/include \
		-L {{ray_lib_path}}/lib \
		-lraylib -lm -lpthread -ldl -lrt \
		-o main.out

build-forest:
	gcc main.c \
		-DMAIN_BG_COLOR=0x1B2D1BFF \
		-DMAIN_TEXT_SIZE=20 \
		-DMAIN_TEXT_COLOR=0x90EE90FF \
		-DMAIN_BORDER_COLOR=0x228B22FF \
		-DINPUT_BG_COLOR=0x2F4F2FFF \
		-DINPUT_TEXT_SIZE=20 \
		-DINPUT_TEXT_COLOR=0x90EE90FF \
		-DINPUT_BORDER_COLOR=0x228B22FF \
		-DINPUT_BASE_COLOR=0x2F4F2FFF \
		-DINPUT_BORDER_COLOR_FOCUSED=0x32CD32FF \
		-DINPUT_BASE_COLOR_FOCUSED=0x3D5A3DFF \
		-DINPUT_TEXT_COLOR_FOCUSED=0x98FB98FF \
		-DINPUT_BORDER_WIDTH=2 \
		-DINPUT_TEXT_PADDING=5 \
		-DPSTYLES_TEXT_COLOR=RED \
		-DPSTYLES_TIMER_COLOR=ORANGE \
		-DBG_COLOR=DARKGREEN \
		-I {{ray_lib_path}}/include \
		-L {{ray_lib_path}}/lib \
		-lraylib -lm -lpthread -ldl -lrt \
		-o main.out

commit msg:
	git add . && git commit -m "{{msg}}" && git push

run:
	./main.out

clean:
	rm main.out
